export const mockUserData = {
  id: "user_123456",
  name: "Alex Johnson",
  email: "alex.johnson@example.com",
  avatarUrl: null, // No avatar URL, will use initials
  jobTitle: "Senior Software Engineer",
  company: "Tech Innovations Inc.",
  location: "San Francisco, CA",
  bio: "Passionate software engineer with 8+ years of experience in full-stack development. Specializing in React, Node.js, and cloud architecture.",
  website: "https://alexjohnson.dev",
  linkedin: "https://linkedin.com/in/alexjohnson",
  github: "https://github.com/alexjohnson",
  memberSince: "January 2023",
  totalCheatsheets: 12,
  savedJobs: 5,

  // Cheatsheets data
  cheatsheets: [
    {
      id: "cs_001",
      jobTitle: "Senior Frontend Developer",
      company: "TechCorp Solutions",
      createdAt: "2023-04-15T10:30:00Z",
      lastViewed: "2023-04-20T14:45:00Z",
      status: "completed",
    },
    {
      id: "cs_002",
      jobTitle: "Full Stack Engineer",
      company: "InnovateTech",
      createdAt: "2023-05-02T09:15:00Z",
      lastViewed: "2023-05-10T11:20:00Z",
      status: "completed",
    },
    {
      id: "cs_003",
      jobTitle: "React Developer",
      company: "WebSolutions Co.",
      createdAt: "2023-06-18T16:45:00Z",
      status: "in-progress",
    },
    {
      id: "cs_004",
      jobTitle: "Software Architect",
      company: "Enterprise Systems",
      createdAt: "2023-07-05T13:10:00Z",
      status: "draft",
    },
    {
      id: "cs_005",
      jobTitle: "DevOps Engineer",
      company: "Cloud Platforms Inc.",
      createdAt: "2023-08-12T08:30:00Z",
      lastViewed: "2023-08-15T10:05:00Z",
      status: "completed",
    },
    {
      id: "cs_006",
      jobTitle: "UI/UX Developer",
      company: "Creative Designs",
      createdAt: "2023-09-03T14:20:00Z",
      status: "in-progress",
    },
    {
      id: "cs_007",
      jobTitle: "Backend Developer",
      company: "Data Systems Ltd.",
      createdAt: "2023-09-25T11:40:00Z",
      status: "draft",
    },
    {
      id: "cs_008",
      jobTitle: "Mobile App Developer",
      company: "AppWorks Studio",
      createdAt: "2023-10-10T15:30:00Z",
      lastViewed: "2023-10-12T09:15:00Z",
      status: "completed",
    },
    {
      id: "cs_009",
      jobTitle: "Machine Learning Engineer",
      company: "AI Innovations",
      createdAt: "2023-11-05T10:00:00Z",
      status: "in-progress",
    },
    {
      id: "cs_010",
      jobTitle: "Product Manager",
      company: "Product Labs",
      createdAt: "2023-11-20T13:45:00Z",
      status: "draft",
    },
    {
      id: "cs_011",
      jobTitle: "QA Engineer",
      company: "Quality Systems",
      createdAt: "2023-12-01T09:30:00Z",
      lastViewed: "2023-12-05T14:10:00Z",
      status: "completed",
    },
    {
      id: "cs_012",
      jobTitle: "Technical Lead",
      company: "Leadership Tech",
      createdAt: "2023-12-15T11:20:00Z",
      status: "in-progress",
    },
  ],

  // Saved jobs data
  savedJobs: [
    {
      id: "job_001",
      title: "Senior Frontend Developer",
      company: "TechCorp Solutions",
      location: "San Francisco, CA",
      type: "Full-time",
      savedAt: "2023-11-10T09:30:00Z",
      url: "https://example.com/jobs/senior-frontend-developer",
      status: "applied",
    },
    {
      id: "job_002",
      title: "Full Stack Engineer",
      company: "InnovateTech",
      location: "Remote",
      type: "Full-time",
      savedAt: "2023-11-15T14:20:00Z",
      url: "https://example.com/jobs/full-stack-engineer",
      status: "saved",
    },
    {
      id: "job_003",
      title: "React Developer",
      company: "WebSolutions Co.",
      location: "New York, NY",
      type: "Contract",
      savedAt: "2023-11-20T11:45:00Z",
      url: "https://example.com/jobs/react-developer",
      status: "interviewing",
    },
    {
      id: "job_004",
      title: "Software Architect",
      company: "Enterprise Systems",
      location: "Boston, MA",
      type: "Full-time",
      savedAt: "2023-12-01T10:15:00Z",
      url: "https://example.com/jobs/software-architect",
      status: "saved",
    },
    {
      id: "job_005",
      title: "DevOps Engineer",
      company: "Cloud Platforms Inc.",
      location: "Seattle, WA",
      type: "Full-time",
      savedAt: "2023-12-10T13:30:00Z",
      url: "https://example.com/jobs/devops-engineer",
      status: "applied",
    },
  ],
}
