name: Ping Health Endpoint Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:       

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping https://job-fit-ai.onrender.com/health/
        run: curl -s -o /dev/null -w "%{http_code}" https://job-fit-ai.onrender.com/health/